### ISSUE TITLE
Unable to build the app in iOS after installation

### ISSUE THREAD

**Issue by vinaydrevankar** [hyochan/react-native-audio-recorder-player#334]
### Hi there, I am unable to build the app. I get below error when i try to build

'setCategory(_:mode:options:)' is only available in iOS 10.0 or newer
### Expected behavior
App should build after installation

### Actual behavior
Build error is shown while building the app

### Steps to reproduce the behabior
Create a project react native project with depolyment target 9 and follow player installation steps
<img width="887" alt="Screenshot 2021-06-22 at 8 22 01 PM" src="https://user-images.githubusercontent.com/59045103/122948241-6650e780-d398-11eb-9785-9b0c8eb330bf.png">

**Comment by Pyroboomka** [comment]
Same issue, package version 3.0.10, builds fine on 2.5.3 in other project.
RN Version: 0.64.2

**Comment by hyochan** [comment]
I think this is on `Apple` that they do not support the older platform version in `Swift`. Therefore, it is expected and I think I have to note this in the readme that from `3.0.0+`, it supports `iOS` platform `10.0` or newer.

**Comment by hyochan** [comment]
Done https://github.com/hyochan/react-native-audio-recorder-player/commit/4354cc914b0d4e6b2116a41cc85ca886488bd436

**Comment by brerdem** [comment]
Hi!

I'm getting this error even I'm on iOS 11.0. Reinstalled pods and cleaned the build folder still no luck

**Comment by hyochan** [comment]
@brerdem Did you follow [post installation](https://github.com/hyochan/react-native-audio-recorder-player#post-installation)?
