### ISSUE TITLE
Fix SDK version 31 for android

### ISSUE THREAD

**Issue by DioSerdar** [hyochan/react-native-audio-recorder-player#388]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.0.12

### Version of React Native
0.64.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Compiles successfully.

### Actual behavior
Build Fails.With a message
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.browser:browser:1.4.0-alpha01.
     AAR metadata file: C:\*****\******\.gradle\caches\transforms-2\files-2.1\e032f7b3cd0a51e4352073c0f400ec41\browser-1.4.0-alpha01\META-INF\com\android\build\gradle\aar-metadata.properties.

### Steps to reproduce the behavior
Set Target SDK version of the root project to lower than 31. Ex : 29
Run the project on android.

fix:
Replace
    implementation "androidx.browser:browser:$androidXBrowser"
With 
   implementation "androidx.browser:browser:1.3.0"

**Comment by ismailonur** [comment]
I have that same problem.

**Comment by enescang** [comment]
Same problem @hyochan :(. Fixed with @DioSerdar 's solution (implementation "androidx.browser:browser:1.3.0"). Please release new version with that

**Comment by robertqin86** [comment]
Might be a good idea to add to your build.gradle(app) `defaultConfig` if the fix is not available at this moment.

```
defaultConfig {
    configurations.all {
                // temp fix until https://github.com/hyochan/react-native-audio-recorder-player/issues/388 is resolved
                resolutionStrategy { force 'androidx.browser:browser:1.3.0' }
    }
   ...
}
```

**Comment by wibimaster** [comment]
@robertqin86 Thanks !
I tried to upgrade build target to 31, then update AndroidManifest with `android:exported="true"`, but at the end it fails with `Error: Error not specified.` when starting a record...
Your fix works !

**Comment by hyochan** [comment]
Should be fixed in `3.2.0`. Thanks for the report!

**Comment by robertqin86** [comment]
Hi @hyochan , so I updated to the `3.2.0` and I'm still getting this error.

```
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.browser:browser:1.4.0-alpha01.
     AAR metadata file: /Users/qinzhengquan/.gradle/caches/transforms-2/files-2.1/ccd71311daac42bf61432e80dec2d0cc/browser-1.4.0-alpha01/META-INF/com/android/build/gradle/aar-metadata.properties.
```
